from uuid import uuid4

from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _

from .choices import DesignRuleChoices


class DesignRuleSession(models.Model):
    uuid = models.UUIDField(default=uuid4)
    started_at = models.DateTimeField(auto_now_add=True)
    test_result = models.FileField(settings.MEDIA_FOLDER_FILES['testsession_log'], blank=True, null=True, default=None, help_text=_("The HTML log generated by Newman"))
    json_result = models.TextField(blank=True, null=True, default=None, help_text=_("The JSON log generated by Newman"))
    api_endpoint = models.URLField()


class DesignRuleResult(models.Model):
    uuid = models.UUIDField(default=uuid4)
    design_rule = models.ForeignKey(DesignRuleSession, on_delete=models.CASCADE, related_name="results")
    rule_type = models.CharField(max_length=50, default="", choices=DesignRuleChoices.choices)
    success = models.BooleanField(default=False, blank=True)
    errors = models.TextField(default="")

    class Meta:
        ordering = ('design_rule', )
