# Generated by Django 2.2.1 on 2019-06-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0076_auto_20190606_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='cluster',
        ),
    ]
