# Generated by Django 2.2.1 on 2019-06-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0077_remove_session_cluster'),
        ('testsession', '0075_auto_20190614_1232'),
    ]

    operations = [
    ]
