# Generated by Django 2.2.1 on 2019-06-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0075_auto_20190614_1232'),
        ('testsession', '0077_remove_session_cluster'),
    ]

    operations = [
    ]
