# Generated by Django 2.2.1 on 2019-06-20 12:50

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    session = apps.get_model('testsession', 'session')
    for s in session.objects.all():
        s.uuid = uuid.uuid4()
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0078_merge_20190620_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='session',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
