# Generated by Django 2.2.1 on 2019-06-20 13:08

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    session = apps.get_model('testsession', 'sessionLog')
    for s in session.objects.all():
        s.uuid = uuid.uuid4()
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0079_auto_20190620_1450'),
    ]
    operations = [
        migrations.AddField(
            model_name='sessionLog',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='sessionLog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
