# Generated by Django 2.2.1 on 2019-06-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0078_merge_20190620_1416'),
        ('testsession', '0079_auto_20190620_1040'),
    ]

    operations = [
    ]
