# Generated by Django 2.2.1 on 2019-06-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0080_auto_20190620_1508'),
        ('testsession', '0080_merge_20190620_1651'),
    ]

    operations = [
    ]
