# Generated by Django 2.2.1 on 2019-06-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0081_merge_20190621_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='ZGW_images',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
