# Generated by Django 2.2.1 on 2019-07-03 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0082_auto_20190626_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='sessiontype',
            options={'ordering': ('name',), 'verbose_name': 'Session Ttype', 'verbose_name_plural': 'Sessions type'},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={'verbose_name': 'Test Session', 'verbose_name_plural': 'Test Sessions'},
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testsession.SessionType', verbose_name='Session type'),
        ),
        migrations.AlterField(
            model_name='session',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='session',
            name='stopped',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stopped at'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='application',
            field=models.CharField(max_length=200, null=True, verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='role',
            field=models.CharField(max_length=200, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='standard',
            field=models.CharField(max_length=200, null=True, verbose_name='Standard'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='version',
            field=models.CharField(max_length=200, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='vngendpoint',
            name='path',
            field=models.CharField(blank=True, default='', help_text='Path url that is appended in the front end page. The path must contain the slash at                             the beginning. E.g. /zrc/api/v1/', max_length=200),
        ),
        migrations.AlterField(
            model_name='vngendpoint',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=8080),
        ),
    ]
