# Generated by Django 2.2.1 on 2019-07-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0083_auto_20190703_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
