# Generated by Django 2.2.3 on 2019-08-05 15:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0084_sessiontype_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioCaseCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sessiontype',
            options={'ordering': ('name',), 'verbose_name': 'Session Type', 'verbose_name_plural': 'Sessions type'},
        ),
        migrations.AlterField(
            model_name='scenariocase',
            name='vng_endpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='testsession.VNGEndpoint'),
        ),
        migrations.AlterField(
            model_name='vngendpoint',
            name='path',
            field=models.CharField(blank=True, default='', help_text='Path url that is appended in the front end page. The path must contain the slash at                             the beginning. E.g. /zrc/api/v1/', max_length=200, validators=[django.core.validators.RegexValidator(code='Invalid_path', message='The path must start with a slash', regex='^/')]),
        ),
        migrations.AlterField(
            model_name='vngendpoint',
            name='url',
            field=models.URLField(blank=True, default=None, help_text='Base url (host of the service). E.g. http://ref.tst.vng.cloud, without the ending slash.', null=True, validators=[django.core.validators.RegexValidator(code='Invalid_url', inverse_match=True, message='The url must not contain a final slash', regex='/$')]),
        ),
        migrations.AddField(
            model_name='scenariocase',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testsession.ScenarioCaseCollection'),
        ),
        migrations.AddField(
            model_name='vngendpoint',
            name='scenario_collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testsession.ScenarioCaseCollection'),
        ),
    ]
