# Generated by Django 2.2.3 on 2019-08-05 15:31

from django.db import migrations


def create_scenario_case_collections(apps, schema_editor):
    VNGEndpoint = apps.get_model('testsession', 'VNGEndpoint')
    ScenarioCaseCollection = apps.get_model('testsession', 'ScenarioCaseCollection')
    for endpoint in VNGEndpoint.objects.all():
        collection = ScenarioCaseCollection.objects.create(
            name='{} {} scenario case collection'.format(endpoint.session_type.name, endpoint.name)
        )
        for case in endpoint.scenariocase_set.all():
            case.collection = collection
            case.save()
        endpoint.scenario_collection = collection
        endpoint.save()


def remove_scenario_case_collections(apps, schema_editor):
    VNGEndpoint = apps.get_model('testsession', 'VNGEndpoint')
    for endpoint in VNGEndpoint.objects.all():
        for case in endpoint.scenario_collection.scenariocase_set.all():
            case.vng_endpoint = endpoint
            case.collection = None
            case.save()
        endpoint.scenario_collection.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0085_auto_20190805_1731'),
    ]

    operations = [
        migrations.RunPython(create_scenario_case_collections, remove_scenario_case_collections)
    ]
