# Generated by Django 2.2.3 on 2019-08-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0086_auto_20190805_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariocase',
            name='vng_endpoint',
        ),
        migrations.AlterField(
            model_name='scenariocase',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsession.ScenarioCaseCollection'),
        ),
    ]
