# Generated by Django 2.2.4 on 2019-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0087_auto_20190805_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vngendpoint',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='vngendpoint',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
