# Generated by Django 2.2.4 on 2019-09-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0087_auto_20190805_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariocase',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scenariocase',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
