# Generated by Django 2.2.4 on 2019-09-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0088_auto_20190905_1530'),
        ('testsession', '0089_auto_20190830_1705'),
    ]

    operations = [
    ]
