# Generated by Django 2.2.4 on 2019-09-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0088_auto_20190905_0956'),
        ('testsession', '0090_merge_20190909_0913'),
    ]

    operations = [
    ]
