# Generated by Django 2.2.4 on 2019-09-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0092_auto_20190916_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryparamsscenario',
            name='name',
            field=models.CharField(help_text='The name of the query parameter', max_length=100),
        ),
    ]
