# Generated by Django 2.2.4 on 2019-10-04 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0089_auto_20191004_1614'),
        ('testsession', '0093_auto_20190927_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='api',
            field=models.ForeignKey(blank=True, help_text='The API to which this session type belongs', null=True, on_delete=django.db.models.deletion.PROTECT, to='servervalidation.API'),
        ),
    ]
