# Generated by Django 2.2.4 on 2019-10-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0094_auto_20191004_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariocase',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
