# Generated by Django 2.2.4 on 2019-10-17 07:48

from django.db import migrations


def add_dashboard_flatpage(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    Site = apps.get_model('sites', 'Site')
    homepage = FlatPage.objects.create(
        url='/',
        title='Homepage',
        content='homepage'
    )
    homepage.sites.set([Site.objects.first()])

class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0094_auto_20191004_1614'),
    ]

    operations = [
        migrations.RunPython(add_dashboard_flatpage, migrations.RunPython.noop)
    ]
