# Generated by Django 2.2.3 on 2019-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190410_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Maximum 150 characters.', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
