# Generated by Django 2.2.13 on 2020-09-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DesignRules',
            new_name='DesignRule',
        ),
        migrations.CreateModel(
            name='DesignRuleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('api_03', 'API-03: Only apply default HTTP operations'), ('api_09', 'API-09: Implement custom representation if supported'), ('api_16', 'API-16: Use OAS 3.0 for documentation'), ('api_20', 'API-20: Include the major version number only in ihe URI'), ('api_48', 'API-48: Leave off trailing slashes from API endpoints'), ('api_51', 'API-51: Publish OAS at the base-URI in JSON-format')], default='', max_length=50)),
                ('design_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_rules.DesignRule')),
            ],
        ),
    ]
