# Generated by Django 2.2.13 on 2020-09-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0003_auto_20200923_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrulesession',
            name='design_rule',
        ),
        migrations.AddField(
            model_name='designrulesession',
            name='api_endpoint',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designrulesession',
            name='documentation_endpoint',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DesignRule',
        ),
    ]
