# Generated by Django 2.2.13 on 2020-09-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0005_auto_20200925_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrulesession',
            name='documentation_endpoint',
        ),
    ]
