# Generated by Django 2.2.13 on 2020-09-30 14:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0007_auto_20200930_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRuleTestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('api_endpoint', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='designrulesession',
            name='api_endpoint',
        ),
        migrations.AlterField(
            model_name='designrulesession',
            name='json_result',
            field=models.TextField(blank=True, default=None, help_text='This is the downloaded api spec', null=True),
        ),
        migrations.AddField(
            model_name='designrulesession',
            name='test_suite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='design_rules.DesignRuleTestSuite'),
        ),
    ]
