# Generated by Django 2.2.13 on 2020-10-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0114_auto_20201002_1537'),
        ('design_rules', '0008_auto_20200930_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designrulesession',
            options={'ordering': ('-started_at',)},
        ),
        migrations.AddField(
            model_name='designruletestsuite',
            name='api',
            field=models.ForeignKey(blank=True, help_text='The API to which this session type belongs', null=True, on_delete=django.db.models.deletion.PROTECT, to='servervalidation.API'),
        ),
    ]
