# Generated by Django 2.2.13 on 2020-10-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0009_auto_20201002_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designruletestsuite',
            name='api',
        ),
    ]
