# Generated by Django 2.2.13 on 2020-11-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0011_designruletestoption_designruletestversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='designruletestoption',
            name='test_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='design_rules.DesignRuleTestVersion'),
        ),
    ]
