# Generated by Django 2.2.13 on 2020-11-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0012_designruletestoption_test_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrulesession',
            name='test_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='design_rules.DesignRuleTestVersion'),
        ),
        migrations.AddField(
            model_name='designruletestversion',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='designruletestoption',
            name='test_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_options', to='design_rules.DesignRuleTestVersion'),
        ),
    ]
