# Generated by Django 2.2.13 on 2020-11-18 14:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0016_auto_20201111_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='designruleresult',
            name='new_errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None),
        ),
    ]
