# Generated by Django 2.2.13 on 2020-11-18 14:22

from django.db import migrations


def copy_answers(apps, schemas):
    DesignRuleResult = apps.get_model("design_rules.DesignRuleResult")

    for result in DesignRuleResult.objects.all():
        result.new_errors = result.errors.split("\n")
        result.save()


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0017_designruleresult_new_errors'),
    ]

    operations = [
        migrations.RunPython(copy_answers)
    ]
