# Generated by Django 2.2.13 on 2020-11-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0018_auto_20201118_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designruleresult',
            name='errors',
        ),
    ]
