# Generated by Django 2.2.13 on 2020-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0021_auto_20201125_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designruletestsuite',
            name='api_endpoint',
            field=models.URLField(unique=True),
        ),
    ]
