# Generated by Django 2.2.13 on 2020-12-09 14:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0022_auto_20201125_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='designruleresult',
            name='warnings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='designruleresult',
            name='rule_type',
            field=models.CharField(choices=[('api_09', 'API-09 V-17-01-2020: Implement custom representation if supported'), ('api_51', 'API-51 V-17-01-2020: Publish OAS at the base-URI in JSON-format'), ('api_03', 'API-03 V-09-07-2020: Only apply standard HTTP methods'), ('api_16', 'API-16 V-09-07-2020: Use OpenAPI Specification for documentation'), ('api_20', 'API-20 V-09-07-2020: Include the major version number in the URI'), ('api_48', 'API-48 V-09-07-2020: Leave off trailing slashes from URIs'), ('api_51_20200709', 'API-51 V-09-07-2020: Publish OAS document at a standard location in JSON-format'), ('api_53_20200709', 'API-53 V-09-07-2020: Hide irrelevant implementation details'), ('api_54_20200709', 'API-54 V-09-07-2020: Use plural nouns to name collection resources'), ('api_55_20200709', 'API-55 V-09-07-2020: Publish a changelog for API changes between versions'), ('api_56_20200709', 'API-56 V-09-07-2020: Adhere to the Semantic Versioning model when releasing API changes'), ('api_57_20200709', 'API-57 V-09-07-2020: Return the full version number in a response header')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='designruletestoption',
            name='rule_type',
            field=models.CharField(blank=True, choices=[('api_09', 'API-09 V-17-01-2020: Implement custom representation if supported'), ('api_51', 'API-51 V-17-01-2020: Publish OAS at the base-URI in JSON-format'), ('api_03', 'API-03 V-09-07-2020: Only apply standard HTTP methods'), ('api_16', 'API-16 V-09-07-2020: Use OpenAPI Specification for documentation'), ('api_20', 'API-20 V-09-07-2020: Include the major version number in the URI'), ('api_48', 'API-48 V-09-07-2020: Leave off trailing slashes from URIs'), ('api_51_20200709', 'API-51 V-09-07-2020: Publish OAS document at a standard location in JSON-format'), ('api_53_20200709', 'API-53 V-09-07-2020: Hide irrelevant implementation details'), ('api_54_20200709', 'API-54 V-09-07-2020: Use plural nouns to name collection resources'), ('api_55_20200709', 'API-55 V-09-07-2020: Publish a changelog for API changes between versions'), ('api_56_20200709', 'API-56 V-09-07-2020: Adhere to the Semantic Versioning model when releasing API changes'), ('api_57_20200709', 'API-57 V-09-07-2020: Return the full version number in a response header')], default='', max_length=50),
        ),
    ]
