# Generated by Django 2.2.13 on 2021-01-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0023_auto_20201209_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='designruletestsuite',
            name='specification_url',
            field=models.URLField(blank=True),
        ),
    ]
