# Generated by Django 2.2.1 on 2019-06-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0064_auto_20190620_1040'),
        ('servervalidation', '0063_auto_20190620_1508'),
    ]

    operations = [
    ]
