# Generated by Django 2.2.1 on 2019-07-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0066_auto_20190628_1137'),
        ('servervalidation', '0066_auto_20190703_1247'),
    ]

    operations = [
    ]
