# Generated by Django 2.2.1 on 2019-07-11 14:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0067_merge_20190703_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenario',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
