# Generated by Django 2.2.4 on 2019-08-27 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0071_auto_20190823_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmantest',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='postmantest',
            name='version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
    ]
