# Generated by Django 2.2.4 on 2019-08-27 09:47

from django.db import migrations

def add_names(apps, schema_editor):
    PostmanTest = apps.get_model('servervalidation', 'PostmanTest')
    for test in PostmanTest.objects.all():
        filename = test.validation_file.original_filename
        test.name = filename.split('.')[0]
        test.save()

def remove_names(apps, schema_editor):
    PostmanTest = apps.get_model('servervalidation', 'PostmanTest')
    for test in PostmanTest.objects.all():
        test.name = ''
        test.save()



class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0072_auto_20190827_1146'),
    ]

    operations = [
        migrations.RunPython(add_names, remove_names)
    ]
