# Generated by Django 2.2.4 on 2019-09-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0074_auto_20190827_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverheader',
            name='server_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
        migrations.AlterUniqueTogether(
            name='postmantest',
            unique_together={('name', 'version')},
        ),
    ]
