# Generated by Django 2.2.4 on 2019-09-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0076_auto_20190905_1519'),
        ('servervalidation', '0076_auto_20190902_1556'),
    ]

    operations = [
    ]
