# Generated by Django 2.2.4 on 2019-09-19 14:49

from django.db import migrations


def create_scheduled_scenarios(apps, schema_editor):
    ServerRun = apps.get_model('servervalidation', 'ServerRun')
    Environment = apps.get_model('servervalidation', 'Environment')
    ScheduledTestScenario = apps.get_model('servervalidation', 'ScheduledTestScenario')
    for server_run in ServerRun.objects.all():
        environment, _ = Environment.objects.get_or_create(
            test_scenario=server_run.test_scenario,
            name=f"{server_run.test_scenario.name} {server_run.started}",
            user=server_run.user,
        )

        if server_run.scheduled:
            ScheduledTestScenario.objects.get_or_create(
                test_scenario=server_run.test_scenario,
                user=server_run.user,
                environment=environment
            )

        for endpoint in server_run.endpoint_set.all():
            endpoint.environment = environment
            endpoint.save()

        for header in server_run.serverheader_set.all():
            header.environment = environment
            header.save()

        server_run.environment = environment
        server_run.save()

class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0078_auto_20190919_1641'),
    ]

    operations = [
        migrations.RunPython(create_scheduled_scenarios, migrations.RunPython.noop)
    ]
