# Generated by Django 2.2.4 on 2019-09-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0080_auto_20190920_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtestscenario',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether this schedule is still active or not'),
        ),
    ]
