# Generated by Django 2.2.4 on 2019-09-23 09:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0081_auto_20190920_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenario',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The universally unique identifier of this test scenario', null=True),
        ),
    ]
