# Generated by Django 2.2.4 on 2019-09-23 09:42

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    TestScenario = apps.get_model('servervalidation', 'TestScenario')
    for row in TestScenario.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0082_auto_20190923_1141'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
