# Generated by Django 2.2.4 on 2019-09-23 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0083_auto_20190923_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscenario',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
