# Generated by Django 2.2.4 on 2019-09-26 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0086_auto_20190926_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(help_text='The name of this environment', max_length=100),
        ),
    ]
