# Generated by Django 2.2.4 on 2019-10-04 14:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0088_auto_20191004_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenario',
            name='api',
            field=models.ForeignKey(blank=True, help_text='The API to which this test scenario belongs', null=True, on_delete=django.db.models.deletion.PROTECT, to='servervalidation.API'),
        ),
    ]
