# Generated by Django 2.2.4 on 2019-10-10 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0089_auto_20191004_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtestscenario',
            name='environment',
            field=models.OneToOneField(blank=True, help_text='The environment that will be used for provider runs of this scheduled scenario', null=True, on_delete=django.db.models.deletion.PROTECT, to='servervalidation.Environment'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledtestscenario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='scheduledtestscenario',
            name='test_scenario',
        ),
        migrations.RemoveField(
            model_name='scheduledtestscenario',
            name='user',
        ),
    ]
