# Generated by Django 2.2.4 on 2019-10-29 13:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0091_auto_20191015_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmantest',
            name='validation_file',
            field=models.FileField(blank=True, default=None, help_text='The actual file containing the Postman collection', null=True, upload_to=''),
        ),
    ]
