# Generated by Django 2.2.4 on 2019-11-08 11:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0091_auto_20191015_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmantest',
            old_name='validation_file',
            new_name='_validation_file',
        ),
    ]
