# Generated by Django 2.2.4 on 2019-11-01 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0092_auto_20191029_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'permissions': (('create_scenario_for_api', 'Create a test scenario for this API'),)},
        ),
    ]
