# Generated by Django 2.2.4 on 2019-11-08 11:57

import os
import shutil

from django.conf import settings
from django.db import migrations
from filer.models import File


def migrate_postmantest_validation_files(apps, schema_editor):
    PostmanTest = apps.get_model('servervalidation', 'PostmanTest')
    for postmantest in PostmanTest.objects.all():
        validation_file = postmantest._validation_file

        filepath = os.path.join(settings.MEDIA_ROOT, validation_file.file.name)

        new_path = settings.MEDIA_ROOT

        # To ensure that the name of the file is no longer than 100 characters
        if len(validation_file.original_filename) > 99:
            name = validation_file.original_filename[:96] + ".json"
            new_path = os.path.join(new_path, name)

        shutil.copy(filepath, new_path)

        postmantest.validation_file = validation_file.original_filename
        postmantest.save()

class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0093_auto_20191108_1255'),
    ]

    operations = [
        migrations.RunPython(migrate_postmantest_validation_files, migrations.RunPython.noop)
    ]
