# Generated by Django 2.2.4 on 2019-11-08 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0094_auto_20191108_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmantest',
            name='_validation_file',
        ),
    ]
