# Generated by Django 2.2.4 on 2019-11-08 13:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0097_auto_20191108_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='server_run',
            field=models.ForeignKey(blank=True, help_text='The provider run to which this endpoint belongs', null=True, on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='test_scenario',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, to='servervalidation.TestScenario'),
        ),
        migrations.AlterField(
            model_name='postmantest',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='postmantest',
            name='test_scenario',
            field=models.ForeignKey(help_text='The name of the test scenario to which this Postman test is linked', on_delete=django.db.models.deletion.CASCADE, to='servervalidation.TestScenario'),
        ),
        migrations.AlterField(
            model_name='postmantestresult',
            name='server_run',
            field=models.ForeignKey(help_text='The provider run which this result belongs to', on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
        migrations.AlterField(
            model_name='scheduledtestscenario',
            name='environment',
            field=models.OneToOneField(blank=True, help_text='The environment that will be used for provider runs of this scheduled scenario', null=True, on_delete=django.db.models.deletion.CASCADE, to='servervalidation.Environment'),
        ),
        migrations.AlterField(
            model_name='serverheader',
            name='server_run',
            field=models.ForeignKey(blank=True, help_text='The provider run for which this header was used', null=True, on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
        migrations.AlterField(
            model_name='serverrun',
            name='environment',
            field=models.ForeignKey(blank=True, help_text='The environment that will be used for this provider run', null=True, on_delete=django.db.models.deletion.CASCADE, to='servervalidation.Environment'),
        ),
        migrations.AlterField(
            model_name='serverrun',
            name='scheduled_scenario',
            field=models.ForeignKey(blank=True, help_text='The scheduled test scenario for which this provider run was executed', null=True, on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ScheduledTestScenario'),
        ),
        migrations.AlterField(
            model_name='serverrun',
            name='test_scenario',
            field=models.ForeignKey(help_text='The test scenario for which this provider run was executed', on_delete=django.db.models.deletion.CASCADE, to='servervalidation.TestScenario'),
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The universally unique identifier of this test scenario', unique=True),
        ),
        migrations.AlterField(
            model_name='testscenariourl',
            name='test_scenario',
            field=models.ForeignKey(help_text='The test scenario to which this variable is linked', on_delete=django.db.models.deletion.CASCADE, to='servervalidation.TestScenario'),
        ),
    ]
