# Generated by Django 2.2.4 on 2019-11-14 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0100_auto_20191111_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrun',
            name='software_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
