# Generated by Django 2.2.4 on 2019-11-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0102_auto_20191115_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrun',
            name='product_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='serverrun',
            name='software_product',
            field=models.CharField(blank=True, default='', help_text='Name of the software tested by this provider test', max_length=100),
        ),
        migrations.AlterField(
            model_name='serverrun',
            name='software_version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='serverrun',
            name='supplier_name',
            field=models.CharField(blank=True, default='', help_text='Name of the supplier of the software product', max_length=100),
        ),
    ]
