# Generated by Django 2.2.4 on 2019-11-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0103_auto_20191115_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='product_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='environment',
            name='software_product',
            field=models.CharField(blank=True, default='', help_text='Name of the software tested by tests for this environment', max_length=100),
        ),
        migrations.AddField(
            model_name='environment',
            name='supplier_name',
            field=models.CharField(blank=True, default='', help_text='Name of the supplier of the software product', max_length=100),
        ),
    ]
