# Generated by Django 2.2.4 on 2019-11-29 10:29

from django.db import migrations


def migrate_product_data_to_environments(apps, schema_editor):
    fields = ["product_role", "software_product", "supplier_name"]
    ServerRun = apps.get_model('servervalidation', 'ServerRun')
    for server_run in ServerRun.objects.all():
        env = server_run.environment
        for field in fields:
            value = getattr(server_run, field, "")
            setattr(env, field, value)
        env.save()

def migrate_product_data_to_provider_runs(apps, schema_editor):
    fields = ["product_role", "software_product", "supplier_name"]
    ServerRun = apps.get_model('servervalidation', 'ServerRun')
    for server_run in ServerRun.objects.all():
        env = server_run.environment
        for field in fields:
            value = getattr(env, field, "")
            setattr(server_run, field, value)
        server_run.save()

class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0104_auto_20191129_1128'),
    ]

    operations = [
        migrations.RunPython(migrate_product_data_to_environments, migrate_product_data_to_provider_runs)
    ]
