# Generated by Django 2.2.4 on 2019-11-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0105_auto_20191129_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverrun',
            name='product_role',
        ),
        migrations.RemoveField(
            model_name='serverrun',
            name='software_product',
        ),
        migrations.RemoveField(
            model_name='serverrun',
            name='supplier_name',
        ),
    ]
