# Generated by Django 2.2.4 on 2019-12-05 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0106_auto_20191129_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverrun',
            old_name='software_version',
            new_name='build_version',
        ),
    ]
